apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
  namespace: kube-system
spec:
  api:
    address: 100.89.189.66
    ca:
      certificatesExpireAfter: 8760h0m0s
      expiresAfter: 87600h0m0s
    k0sApiPort: 9443
    port: 6443
  controllerManager: {}
  extensions:
    helm:
      concurrencyLevel: 5
      repositories:
        - name: cilium
          url: https://helm.cilium.io/
      charts:
        - name: cilium
          chartname: cilium/cilium
          version: "1.19.0"
          namespace: kube-system
          values: |
            ipam:
              mode: kubernetes
            kubeProxyReplacement: true
            k8sServiceHost: 100.89.189.66
            k8sServicePort: "6443"
            hubble:
              relay:
                enabled: true
              ui:
                enabled: true
            prometheus:
              enabled: true
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    # Use Cilium as the CNI provider
    provider: custom
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    kubeProxy:
      disabled: true
    clusterDomain: cluster.local
    dualStack:
      enabled: false
    nodeLocalLoadBalancing:
      enabled: false
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132
      type: EnvoyProxy
  scheduler: {}
  storage:
    etcd:
      ca:
        certificatesExpireAfter: 8760h0m0s
        expiresAfter: 87600h0m0s
      peerAddress: 100.89.189.66
    type: etcd
  telemetry:
    enabled: false
