apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openfga-route
  namespace: openfga
spec:
  ingressClassName: traefik
  rules:
    - host: protomakerlab.tail37e3dd.ts.net
      http:
        paths:
          - backend:
              service:
                name: openfga
                port:
                  number: 8080
            path: /openfga
            pathType: Prefix