annotations:
  artifacthub.io/signKey: |
    fingerprint: 2EAE29FDF8A387050C82CD5ABBDD4FD6A1FFCBF6
    url: https://raw.githubusercontent.com/fission/fission-charts/main/public_key/pgp_keys.asc
apiVersion: v2
appVersion: v1.27.0
description: Fission is a fast serverless framework for Kubernetes.
home: https://fission.io/
icon: https://fission.io/images/fission-logo-white.svg
keywords:
- fission
- serverless
- platform
- faas
- functions
- Integration & Delivery
kubeVersion: '>=1.32.0-0'
maintainers:
- email: vishal@infracloud.io
  name: Vishal Biyani
- email: sanket@infracloud.io
  name: Sanket Sudake
name: fission-all
sources:
- https://github.com/fission/fission
- https://github.com/fission/keda-connectors
type: application
version: 1.27.0
