watchAnyNamespace: true

# 1. Enable dynamic configuration via environment variables
envs:
  config:
    DYNAMIC_CONFIG_ENABLED: "true"

yamlApplicationConfigConfigMap:
  name: kafka-ui-config
  keyName: config.yml