datastore:
  engine: postgres
  existingSecret: openfga-postgres-secret
  secretKeys:
    uriKey: uri
    usernameKey: username
    passwordKey: password
  applyMigrations: true
  waitForMigrations: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80